# Generated by Django 5.0.3 on 2024-03-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenthdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenth_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twelfthdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twelfth_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
