# Generated by Django 5.1 on 2024-09-13 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('board_name', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=4)),
                ('admission_year', models.DateTimeField()),
                ('passing_year', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='institute_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
